### ISSUE TITLE
How to pass variable parameter to function?

### ISSUE THREAD

**Issue by Ziaeemehr** [neurophysik/jitcode#26]
It's Kuramoto model, I defined coupling `g=Symbole("g")` as parameter.
I wand to pass the coupling to `kuramotos_f()`.
`if else`  statement  at `main` function just check for presence of compiled file.

one more question is that is it possible to pass the adjacency matrix also as a parameter?

```python
import os
import numpy as np
import pylab as plt
from jitcode import jitcode, y
from numpy.random import choice
from numpy.random import uniform
from symengine import sin, Symbol


def kuramotos_f():  # kuramotos_f(g, A)??
    for i in range(n):
        coupling_sum = sum(sin(y(j)-y(i))
                           for j in range(n)
                           if A[i, j])
        yield omega[i] + g / (n-1)*coupling_sum


def main(coupling, time_simulation):
        cfilename = "data/jitced.so"
        if not os.path.exists(cfilename):

            I = jitcode(kuramotos_f, n=n, control_pars=[g])
            I.generate_f_C()
            I.compile_C()
            I.save_compiled(overwrite=True, destination=cfilename)
        else:
            I = jitcode(n=n, module_location=cfilename)
            
        I.set_parameters(coupling)
        I.set_integrator("dopri5", atol=1e-6, rtol=1e-5)
        I.set_initial_value(initial_state, time=0.0)

        times = range(0, time_simulation)
        phases = np.empty((len(times), n))

        for i in range(len(times)):
            phases[i, :] = I.integrate(times[i]) % (2*np.pi)
    
        return times, phases


n = 100
q = 0.2
g = Symbol("g")
time_simulation = 2001

if __name__ == "__main__":

    np.random.seed(1)

    A = choice([1, 0], size=(n, n), p=[q, 1-q])
    initial_state = uniform(0, 2*np.pi, n)
    omega = uniform(-0.5, 0.5, n)
    omega.sort()
    
    coupling = 3.0
    times, phases = main(coupling, time_simulation)
```

Thank you for any guide.

**Comment by Wrzlprmft** [comment]
This seems fine to me, though it’s bit weirdly ordered and you have to be careful about the namespaces.

What happens is that `A` and `g` are defined in the main namespace, before `main` is called in the very last line. `main` then calls `jitcode` (if not pre-compiled) which in turn calls `kuramotos_f`. The latter then doesn’t have `A` and `g` defined in its main name space and thus defaults back to the main name space for them (where they are defined). This is a pure Python thing.

I would refrain from using a `main` function in Python. It’s just unnecessarily convoluting things. I would also only use `if __name__ == "__main__":` if you really need it. It may help you to note that you can define functions within another function, loop body or `if` body in Python. So you can define `kuramotos_f` in `main` for example.

The generator functions passed to `jitcode` cannot have any parameters, since that is not necessary.

> is it possible to pass the adjacency matrix also as a parameter?

You can theoretically use an adjacency matrix, whose entries are symbols, which in turn are parameters. However, I strongly advise against that since it would void the advantages gained by the just-in-time compilation, namely that you do not have a lot of multiplications with zero and lookups happening at runtime. If you want to change the adjacency matrix, it is more efficient to recompile. The only exception is if you only want to change a small number of connection. In that case you can make the respective entries in the adjacency matrix symbolic and use them as parameters. Mind that JiTCODE doesn’t really get to know that you are using a matrix.

----

A final remark: Using `rtol` for phase oscillators does not really make sense, since zero is not a unique value.

**Comment by Ziaeemehr** [comment]
Thank you for quick response, that was clear and informative.
