### ISSUE TITLE
Module name has already been used in this instance of Python

### ISSUE THREAD

**Issue by Ziaeemehr** [neurophysik/jitcode#34]
Dear developers,

I get the following error when I try to compile a model in jupyter notebook for the second time:
```
"Module name has already been used in this instance of Python."
```

suppose the `modulename` is 'KM', I delete the module manually to be abel to compile the code or restart the kernel.

```
from sys import modules
del modules['KM']
```

is this check necessary or can be handled by passing an argument for example to `compile_C()` ?
I am trying to hide the complexities as much as possible from the end user.

**Comment by Wrzlprmft** [comment]
The check is necessary because Python’s import machinery cannot import a module with the same name twice without further ado. I am surprised that you could even circumvent this problem at all. As far as I can tell from a quick glance, `del modules['KM']` is not robust or recommended. Unfortunately, module naming is somewhat tedious since Python’s design in this respect wasn’t made with dynamic stuff like done by JiTC*DE in mind.

Unless you try to force the module name, JiTC*DE enumerates modules (using `jitcxde_common.strings.count_up`). Does this suffice for you? If not, can you give me a bit more detail on what you are trying to achieve?

**Comment by Ziaeemehr** [comment]
For conditions to run the simulation ones, I don't set the modulename and that's resolve the issue,
but in cases that I need to compile once and repeatedly use the compiled file, I think we need to pass the `modulename` right?

here is the steps:
- using compile_C() to compile and save the *.so file.
- using `jitcode` with `module_location` to access the `*.so`  file and run repeatedly.
- made some changes, compile again and run in jupyter notebook.
but the third step need to restart or del the module which is not proper for end user.

**Comment by Wrzlprmft** [comment]
I must admit that I am not clear about what you want to do here and where your problem is, but the following may help:

* `modulename` (of `compile_C`) and `destination` (of `save_compiled`) specify the output, i.e., a module to be compiled. (The difference between the two is that `destination` may include a file ending and a folder or may only be a folder.)
* `module_location` specifies the input, i.e., an existing compiled module.
* Recompilation can only possibly happen if you have specified a derivative (`f_sym`) – which does not happen in your snippets.
* Recompilation only happens if you have already compiled (due to automatic compilation or calling `compile_C`) and then either:
    
    * call `compile_C` (which will always compile),
    * call `save_compiled` with a `destination` argument that does not match the module name of the previous compilation (as chosen automatically or specified with `modulename`).

**Comment by Ziaeemehr** [comment]
Thank you for the details. It's quit clear.
I bring some snippest of the code and link to the full notebook in case there is ambiguity.
The control parameter is coupling strength. The purpose is to simulate explosive synchronization to get the hysteresis loop in order parameter.

```python
I = Kuramoto_II(parameters)   # make an instance of class
# compile model and store KM.so file. 
# If I try to call compile again in the jupyter nootebook I get the error for Module name.
So I need to comment it if I want to run the cell again or just restart the kernel of the notebook.
I.compile()                               


def simulateHalfLoop():
    # some code
    for i in range(num_couplings):
        
        I = Kuramoto_II(parameters)           # make an instance of class without compiling
        data = I.simulate(couplings[i])       # simulating by using KM.so file repeatedly
        # some code

# now call the simulateHalkLoop to run on varioue coupling
simulateHalfLoop()
```

```python
class Kuramoto_II:
   # come code

   def compile(self, **kwargs):

        I = jitcode(self.rhs, n=self.N,
                    control_pars=self.control_pars)
        I.generate_f_C(**kwargs)
        I.compile_C(omp=self.use_omp, modulename=self.modulename)
        I.save_compiled(overwrite=True, destination=join(self.output, ''))
   
   def simulate(self, par, **integrator_params):

        I=jitcode(n=self.N,
                    control_pars=self.control_pars,
                    module_location=join(self.output, self.modulename+".so"))
        I.set_integrator(name=self.integration_method,
                         **integrator_params)
        I.set_parameters(par)
        I.set_initial_value(self.initial_state, time=self.t_initial)
        # some code
        for i in range(len(times)):
            phases[i, :]=I.integrate(times[i]) % (2*np.pi)
```

![download](https://user-images.githubusercontent.com/7780103/128514448-625d4e7a-9d57-4daa-b366-7bd6761efc1d.png)


I hope made it clear.
Link to the [notebook](https://github.com/Ziaeemehr/JITCSIM/blob/master/jitcsim/examples/notebooks/07_explosive_synchronization.ipynb).

If user run the cell containing `compile()` again, he\she get module name error.
So the specific question is how to compile code once and run repeatedly, and also not get module name error without restarting kernel in Jupyter notebook.

Sorry for the long codes.

**Comment by Ziaeemehr** [comment]
Maybe it's not a crucial problem, just to define modulename as a string + str(randI()) in the compile(), will resolve the modulename error.
